-- Sample project data for local development and first-run demos.
--
-- Applied by: npx supabase db reset
--
-- These guides are unattributed (createdBy IS NULL) on purpose. Seeding a fixed
-- author would mean shipping a fixed account, and the old default-admin row is
-- exactly what this project removed. Assign ownership yourself if you need it.
--
-- Materials and steps are stored in the legacy string[] shape here. The API
-- normalizes them to the structured shape on read, which also keeps this file
-- honest about what pre-existing data actually looks like.

INSERT INTO "edubuild_projects" (id, title, description, budget, "classLevel", subject, materials, steps, "learningOutcomes", difficulty, rating, image, "videoUrl", status, "createdBy", "createdAt", "updatedAt")
VALUES 
(
  '550e8400-e29b-41d4-a716-446655440001',
  'Solar System Model',
  'Create a 3D model of the solar system using household materials',
  500.00,
  '6-8',
  'Physics',
  '["Styrofoam balls", "Paint", "String", "Cardboard"]'::jsonb,
  '["Paint the balls in different colors", "Arrange them in order", "Connect with string"]'::jsonb,
  '["Understanding planetary order", "Learning about solar system"]'::jsonb,
  'Medium',
  4.5,
  'https://images.unsplash.com/photo-1614730321146-b6fa6a46bcb4?auto=format&fit=crop&q=80&w=1000',
  'https://www.youtube.com/watch?v=libKVRa01L8',
  'approved',
  NULL,
  NOW(),
  NOW()
),
(
  '550e8400-e29b-41d4-a716-446655440003',
  'Water Filtration System',
  'Build a water filtration system using sand, gravel, and activated charcoal',
  800.00,
  '9-10',
  'Chemistry',
  '["Sand", "Gravel", "Activated charcoal", "Plastic bottles", "Coffee filters"]'::jsonb,
  '["Layer materials in bottle", "Pour dirty water", "Observe filtration"]'::jsonb,
  '["Understanding water purification", "Learning about filtration"]'::jsonb,
  'Easy',
  4.8,
  'https://images.unsplash.com/photo-1581093583449-80d50ad9db2a?auto=format&fit=crop&q=80&w=1000',
  '',
  'approved',
  NULL,
  NOW(),
  NOW()
),
(
  '550e8400-e29b-41d4-a716-446655440004',
  'Plant Growth Experiment',
  'Experiment with plant growth under different light conditions',
  300.00,
  '6-8',
  'Biology',
  '["Seeds", "Soil", "Containers", "LED lights", "Water"]'::jsonb,
  '["Plant seeds in soil", "Place under light", "Water regularly", "Record measurements"]'::jsonb,
  '["Understanding photosynthesis", "Learning about plant growth"]'::jsonb,
  'Easy',
  4.6,
  'https://images.unsplash.com/photo-1530836361253-ee1f0449cf06?auto=format&fit=crop&q=80&w=1000',
  '',
  'approved',
  NULL,
  NOW(),
  NOW()
);

INSERT INTO "edubuild_projects" (title, description, budget, "classLevel", subject, materials, steps, "learningOutcomes", difficulty, rating, image, "videoUrl", status, "createdBy", "createdAt", "updatedAt")
VALUES 
(
  'Balloon-Powered Car',
  'A DIY vehicle that demonstrates Newtons Third Law of Motion. It uses the stored potential energy in a balloon to create kinetic energy, propelling the car forward as air escapes.',
  20,
  '6-8',
  'Physics',
  '["Empty plastic bottle", "4 bottle caps", "2 plastic straws", "1 balloon", "2 wooden skewers", "Adhesive tape", "Scissors"]'::jsonb,
  '["Cut two straws to a length slightly wider than the plastic bottle.", "Tape these two straws horizontally across the bottom of the bottle to act as axle holders.", "Poke a hole in the center of each of the 4 bottle caps using a pin or nail.", "Slide a wooden skewer through one straw and attach bottle caps to both ends to create wheels.", "Repeat the process for the second skewer and straw to complete the four-wheel base.", "Secure the neck of a balloon onto the end of a third straw using tight tape (ensure it is airtight).", "Cut a small hole in the top of the bottle and thread the straw through so the balloon sits on top.", "Blow through the straw to inflate the balloon, pinch the end, place the car on a flat surface, and let go!"]'::jsonb,
  '["Newtons Third Law", "Kinetic vs Potential Energy", "Friction"]'::jsonb,
  'Easy',
  4.8,
  'https://plus.unsplash.com/premium_photo-1664302152990-67c94b7e937d?q=80&w=2832&auto=format&fit=crop',
  '',
  'approved',
  NULL,
  NOW(),
  NOW()
),
(
  'Hydraulic Cardboard Arm',
  'A mechanical arm that uses water pressure to move. It demonstrates Pascals Law, showing how pressure applied to a confined fluid is transmitted undiminished.',
  150,
  '6-8',
  'Physics',
  '["Cardboard", "4 Plastic syringes (10ml)", "Old IV tubes or flexible pipes", "Water (colored with ink)", "Zip ties or wire", "Glue gun"]'::jsonb,
  '["Cut cardboard into four long strips for the arm segments and a square base.", "Join segments using wire pivots so they can move freely.", "Connect two syringes with the IV tubing and fill them with colored water (remove air bubbles).", "Mount one syringe to the cardboard arm and the other to the base to act as the controller.", "Pushing the controller syringe will force water into the arm syringe, extending the arm."]'::jsonb,
  '["Pascals Law", "Hydraulics", "Mechanical Engineering"]'::jsonb,
  'Medium',
  4.7,
  'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158',
  '',
  'approved',
  NULL,
  NOW(),
  NOW()
),
(
  'CD Hovercraft',
  'A simple craft that glides on a thin cushion of air. It teaches students about air pressure, friction reduction, and Newtons Second Law.',
  10,
  '6-8',
  'Physics',
  '["Old CD or DVD", "Balloon", "Dish soap bottle pull-top cap", "Super glue or Hot glue"]'::jsonb,
  '["Close the pop-top cap of the dish soap bottle.", "Glue the base of the cap over the center hole of the CD, ensuring an airtight seal.", "Inflate a balloon and stretch its neck over the closed pop-top cap.", "Place the CD on a very smooth surface (like a glass table or tile).", "Open the pop-top; as air escapes under the CD, it creates a lift that lets it glide frictionlessly."]'::jsonb,
  '["Air Pressure", "Friction", "Newtons Second Law"]'::jsonb,
  'Easy',
  4.5,
  'https://images.unsplash.com/photo-1542831371-d531d36971e6',
  '',
  'approved',
  NULL,
  NOW(),
  NOW()
),
(
  'Solar Pizza Box Oven',
  'A functional oven that cooks using only sunlight. It demonstrates the Greenhouse Effect, reflection, and thermal insulation.',
  50,
  '6-8',
  'Physics',
  '["Pizza box", "Aluminum foil", "Black construction paper", "Plastic wrap", "Clear tape", "Wooden skewer"]'::jsonb,
  '["Cut a flap in the lid of the pizza box, leaving one edge attached.", "Line the inside of the flap with aluminum foil to reflect sunlight.", "Line the bottom of the box with black paper to absorb heat.", "Tape plastic wrap over the opening in the lid to create an airtight window.", "Use a skewer to prop the flap open at an angle to reflect sun into the box."]'::jsonb,
  '["Greenhouse Effect", "Heat Transfer", "Solar Energy"]'::jsonb,
  'Medium',
  4.6,
  'https://images.unsplash.com/photo-1629088667623-01311029e000?q=80&w=2670&auto=format&fit=crop',
  '',
  'approved',
  NULL,
  NOW(),
  NOW()
),
(
  'Shoebox Periscope',
  'An optical instrument used to see objects over or around obstacles. It demonstrates how light reflects off plane mirrors at 45-degree angles.',
  40,
  '6-8',
  'Physics',
  '["Long cardboard box (like a tall cracker or shoebox)", "Two small rectangular mirrors", "Scissors", "Tape"]'::jsonb,
  '["Cut a square window at the top left and bottom right of the long box.", "Glue the first mirror inside the top window at exactly a 45-degree angle.", "Glue the second mirror inside the bottom window, also at a 45-degree angle, facing the first mirror.", "Ensure the mirrors are parallel to each other.", "Look through the bottom window to see what is visible above the top window."]'::jsonb,
  '["Reflection of Light", "Optics", "Angles"]'::jsonb,
  'Easy',
  4.3,
  'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d',
  '',
  'approved',
  NULL,
  NOW(),
  NOW()
),
(
  'Simple Homopolar Motor',
  'The simplest electric motor possible. It uses the Lorentz Force to create motion from electricity and magnetism.',
  100,
  '6-8',
  'Physics',
  '["1 AA Battery", "Neodymium magnet (circular)", "Thick copper wire", "Pliers"]'::jsonb,
  '["Place the neodymium magnet on the negative (flat) end of the AA battery.", "Stand the battery upright on the magnet.", "Bend the copper wire into a shape (like a heart or a spiral) so the center touches the top positive terminal.", "Ensure the bottom ends of the wire lightly touch the sides of the magnet.", "Once the circuit is closed, the wire will start spinning rapidly around the battery."]'::jsonb,
  '["Electromagnetism", "Lorentz Force", "Circuits"]'::jsonb,
  'Medium',
  4.8,
  'https://images.unsplash.com/photo-1517420704952-d9f39e95b43e',
  '',
  'approved',
  NULL,
  NOW(),
  NOW()
),
(
  'Rubber Band Helicopter',
  'A flying toy that demonstrates potential and kinetic energy. Winding the rubber band stores elastic potential energy that converts into mechanical lift.',
  30,
  '6-8',
  'Physics',
  '["Cardboard", "Heavy-duty rubber band", "Paperclip", "Plastic propeller (recycled from a toy)", "Wooden skewer", "Tape"]'::jsonb,
  '["Cut a small rectangular frame from cardboard to act as the body.", "Attach a plastic propeller to the top of a wooden skewer.", "Bend a paperclip into a hook and attach it to the bottom of the skewer.", "Loop a rubber band between the paperclip hook and the bottom of the cardboard frame.", "Wind the propeller to twist the rubber band tightly.", "Release the propeller and watch it fly as the band untwists."]'::jsonb,
  '["Potential Energy", "Kinetic Energy", "Aerodynamics"]'::jsonb,
  'Medium',
  4.5,
  'https://images.unsplash.com/photo-1563214539-756ef1986427?q=80&w=2753&auto=format&fit=crop',
  '',
  'approved',
  NULL,
  NOW(),
  NOW()
),
(
  'Newspaper Bridge',
  'A structural challenge where students build a bridge from paper to learn about tension, compression, and truss designs.',
  10,
  '6-8',
  'Physics',
  '["Old newspapers", "Adhesive tape", "Scissors", "Ruler"]'::jsonb,
  '["Roll individual newspaper sheets tightly into thin, solid tubes and secure with tape.", "Create triangles by taping three tubes together (triangles are the strongest shape).", "Build two main side supports (trusses) using these triangles.", "Connect the two side trusses with horizontal cross-beams.", "Place a flat piece of cardboard on top to create the road deck.", "Test the weight capacity by adding small stones or coins in the center."]'::jsonb,
  '["Structural Engineering", "Tension and Compression", "Force Distribution"]'::jsonb,
  'Easy',
  4.4,
  'https://images.unsplash.com/photo-1506424482853-bb0902494e75?q=80&w=2938&auto=format&fit=crop',
  '',
  'approved',
  NULL,
  NOW(),
  NOW()
),
(
  'Cardboard Catapult',
  'A machine that uses elasticity to launch projectiles, teaching students about force, leverage, and parabolic motion.',
  20,
  '6-8',
  'Physics',
  '["Cardboard", "Rubber bands", "Plastic bottle cap", "Wooden skewers", "Glue gun"]'::jsonb,
  '["Build a rectangular base using thick cardboard strips.", "Glue two triangular cardboard pieces vertically on the base to hold the pivot.", "Push a skewer through the triangles to act as a pivot axis.", "Attach a long cardboard arm to the skewer.", "Loop a rubber band from the front of the base to the arm for tension.", "Glue a bottle cap to the end of the arm, load a paper ball, and launch!"]'::jsonb,
  '["Projectile Motion", "Elasticity", "Simple Machines"]'::jsonb,
  'Easy',
  4.7,
  'https://images.unsplash.com/photo-1516743618174-8aa47b6a4a11?q=80&w=2787&auto=format&fit=crop',
  '',
  'approved',
  NULL,
  NOW(),
  NOW()
),
(
  'Plastic Bottle Water Rocket',
  'A high-pressure rocket that uses water as a propellant to demonstrate Newtons Third Law (Action-Reaction).',
  50,
  '6-8',
  'Physics',
  '["2L Plastic bottle", "Cork", "Bicycle pump", "Ball needle adapter", "Cardboard (for fins)"]'::jsonb,
  '["Tape three cardboard fins to the neck of the bottle so it can stand upright.", "Fill the bottle 1/3 full with water.", "Push a bicycle pump needle through a cork.", "Fit the cork tightly into the bottle mouth.", "Turn the rocket over (fins down), pump air until the pressure forces the cork out, launching the rocket."]'::jsonb,
  '["Newtons Laws", "Pressure", "Aerodynamics"]'::jsonb,
  'Hard',
  4.9,
  'https://images.unsplash.com/photo-1517976487492-5750f3195933',
  '',
  'approved',
  NULL,
  NOW(),
  NOW()
),
(
  'Water Filtration System',
  'A multi-layered filter that cleans water through physical filtration, demonstrating porosity and gravity.',
  30,
  '6-8',
  'Physics',
  '["Plastic bottle", "Cotton balls", "Fine sand", "Gravel", "Small stones", "Muddy water"]'::jsonb,
  '["Cut the bottom off a plastic bottle and flip it upside down (cap facing down).", "Place cotton balls near the neck first.", "Add a thick layer of fine sand, followed by gravel, and finally small stones.", "Pour muddy water into the top.", "Observe the clear water dripping out from the cap into a collection cup."]'::jsonb,
  '["Filtration", "Environmental Science", "States of Matter"]'::jsonb,
  'Easy',
  4.5,
  'https://images.unsplash.com/photo-1527377598539-4d64826b653c?q=80&w=2890&auto=format&fit=crop',
  '',
  'approved',
  NULL,
  NOW(),
  NOW()
),
(
  'Shoebox Projector',
  'Uses a convex lens to project smartphone images onto a wall, teaching students about focal length and image inversion.',
  150,
  '6-8',
  'Physics',
  '["Shoebox", "Magnifying glass", "Black paint", "Smartphone", "Tape"]'::jsonb,
  '["Paint the inside of the shoebox black to absorb stray light.", "Cut a circular hole at one end and tape the magnifying glass over it.", "Place your smartphone inside the box, facing the lens.", "Maximize phone brightness and turn off auto-rotate.", "Move the phone back and forth inside the box until the projection on the wall is sharp."]'::jsonb,
  '["Optics", "Lenses", "Light"]'::jsonb,
  'Medium',
  4.6,
  'https://images.unsplash.com/photo-1584905066893-7d5c142dd652?q=80&w=2891&auto=format&fit=crop',
  '',
  'approved',
  NULL,
  NOW(),
  NOW()
),
(
  'Sound Wave Visualizer',
  'A device that uses a laser to show the physical vibrations of sound waves.',
  100,
  '6-8',
  'Physics',
  '["Tin can", "Balloon", "Small mirror piece", "Laser pointer", "Tape"]'::jsonb,
  '["Cut both ends off a tin can.", "Stretch a balloon tightly over one end and secure with tape.", "Glue a tiny mirror shard to the center of the balloon membrane.", "Shine a laser pointer at the mirror so it reflects onto a wall.", "Sing or shout into the open end of the can; the laser will draw patterns on the wall reflecting the sounds frequency."]'::jsonb,
  '["Sound Waves", "Vibrations", "Frequency"]'::jsonb,
  'Medium',
  4.8,
  'https://images.unsplash.com/photo-1478737270239-2f02b77ac6d5',
  '',
  'approved',
  NULL,
  NOW(),
  NOW()
),
(
  'Homemade Compass',
  'Teaches students about Earths magnetic field by magnetizing a simple needle.',
  10,
  '6-8',
  'Physics',
  '["Sewing needle", "Magnet", "Cork slice", "Bowl of water"]'::jsonb,
  '["Stroke a needle with a magnet 50 times in the same direction to magnetize it.", "Push the needle through a small, light slice of cork.", "Place the cork in a bowl of water so it floats freely.", "The needle will automatically rotate to point North-South."]'::jsonb,
  '["Magnetism", "Earth Science", "Navigation"]'::jsonb,
  'Easy',
  4.2,
  'https://images.unsplash.com/photo-1574888764132-7a7167a51bb3?q=80&w=2541&auto=format&fit=crop',
  '',
  'approved',
  NULL,
  NOW(),
  NOW()
);
